/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CycleBuilderRouteImport } from './routes/cycle-builder'
import { Route as PriceHistoryRouteImport } from './routes/price-history'
import { Route as PriceImpactRouteImport } from './routes/price-impact'
import { Route as ConfigurationsIndexRouteImport } from './routes/configurations.index'
import { Route as ConfigurationsIdRouteImport } from './routes/configurations.$id'
import { Route as PartsIndexRouteImport } from './routes/parts.index'
import { Route as PartsIdRouteImport } from './routes/parts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleBuilderRoute = CycleBuilderRouteImport.update({
  id: '/cycle-builder',
  path: '/cycle-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceHistoryRoute = PriceHistoryRouteImport.update({
  id: '/price-history',
  path: '/price-history',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceImpactRoute = PriceImpactRouteImport.update({
  id: '/price-impact',
  path: '/price-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationsIndexRoute = ConfigurationsIndexRouteImport.update({
  id: '/configurations/',
  path: '/configurations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationsIdRoute = ConfigurationsIdRouteImport.update({
  id: '/configurations/$id',
  path: '/configurations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/parts/',
  path: '/parts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIdRoute = PartsIdRouteImport.update({
  id: '/parts/$id',
  path: '/parts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cycle-builder': typeof CycleBuilderRoute
  '/price-history': typeof PriceHistoryRoute
  '/price-impact': typeof PriceImpactRoute
  '/configurations/$id': typeof ConfigurationsIdRoute
  '/parts/$id': typeof PartsIdRoute
  '/configurations/': typeof ConfigurationsIndexRoute
  '/parts/': typeof PartsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cycle-builder': typeof CycleBuilderRoute
  '/price-history': typeof PriceHistoryRoute
  '/price-impact': typeof PriceImpactRoute
  '/configurations/$id': typeof ConfigurationsIdRoute
  '/parts/$id': typeof PartsIdRoute
  '/configurations': typeof ConfigurationsIndexRoute
  '/parts': typeof PartsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cycle-builder': typeof CycleBuilderRoute
  '/price-history': typeof PriceHistoryRoute
  '/price-impact': typeof PriceImpactRoute
  '/configurations/$id': typeof ConfigurationsIdRoute
  '/parts/$id': typeof PartsIdRoute
  '/configurations/': typeof ConfigurationsIndexRoute
  '/parts/': typeof PartsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cycle-builder'
    | '/price-history'
    | '/price-impact'
    | '/configurations/$id'
    | '/parts/$id'
    | '/configurations/'
    | '/parts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cycle-builder'
    | '/price-history'
    | '/price-impact'
    | '/configurations/$id'
    | '/parts/$id'
    | '/configurations'
    | '/parts'
  id:
    | '__root__'
    | '/'
    | '/cycle-builder'
    | '/price-history'
    | '/price-impact'
    | '/configurations/$id'
    | '/parts/$id'
    | '/configurations/'
    | '/parts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CycleBuilderRoute: typeof CycleBuilderRoute
  PriceHistoryRoute: typeof PriceHistoryRoute
  PriceImpactRoute: typeof PriceImpactRoute
  ConfigurationsIdRoute: typeof ConfigurationsIdRoute
  PartsIdRoute: typeof PartsIdRoute
  ConfigurationsIndexRoute: typeof ConfigurationsIndexRoute
  PartsIndexRoute: typeof PartsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle-builder': {
      id: '/cycle-builder'
      path: '/cycle-builder'
      fullPath: '/cycle-builder'
      preLoaderRoute: typeof CycleBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-history': {
      id: '/price-history'
      path: '/price-history'
      fullPath: '/price-history'
      preLoaderRoute: typeof PriceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-impact': {
      id: '/price-impact'
      path: '/price-impact'
      fullPath: '/price-impact'
      preLoaderRoute: typeof PriceImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations/': {
      id: '/configurations/'
      path: '/configurations'
      fullPath: '/configurations/'
      preLoaderRoute: typeof ConfigurationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations/$id': {
      id: '/configurations/$id'
      path: '/configurations/$id'
      fullPath: '/configurations/$id'
      preLoaderRoute: typeof ConfigurationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/': {
      id: '/parts/'
      path: '/parts'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/$id': {
      id: '/parts/$id'
      path: '/parts/$id'
      fullPath: '/parts/$id'
      preLoaderRoute: typeof PartsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CycleBuilderRoute: CycleBuilderRoute,
  PriceHistoryRoute: PriceHistoryRoute,
  PriceImpactRoute: PriceImpactRoute,
  ConfigurationsIdRoute: ConfigurationsIdRoute,
  PartsIdRoute: PartsIdRoute,
  ConfigurationsIndexRoute: ConfigurationsIndexRoute,
  PartsIndexRoute: PartsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
